name: CustomTotems
version: '1.1'
main: net.momirealms.customtotem.CustomTotems
api-version: 1.16
authors: [ XiaoMoMi ]
commands:
  customtotems:
    permission: customtotems.admin
    permission-message: No Permission
